# Generated by Django 3.2.10 on 2025-05-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sheet_owner_number', models.CharField(max_length=20)),
                ('filtered_calls', models.JSONField()),
                ('imei_usage', models.JSONField()),
                ('most_visited_sites', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(max_length=100)),
                ('site_enb_id', models.CharField(max_length=100)),
                ('cell_id', models.CharField(max_length=100)),
                ('site_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('bore', models.FloatField()),
                ('lac_cell_id_ecgi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInformationUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='site_information/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwoGSiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsc', models.CharField(max_length=100, verbose_name='BSC')),
                ('site_name', models.CharField(max_length=200, verbose_name='Site Name')),
                ('site_id', models.CharField(max_length=100, verbose_name='Site ID')),
                ('cell_id', models.CharField(max_length=100, verbose_name='Cell ID')),
                ('geo_city', models.CharField(max_length=100, verbose_name='Geo-City')),
                ('lac', models.CharField(max_length=50, verbose_name='LAC')),
                ('mcc', models.CharField(max_length=10, verbose_name='MCC')),
                ('mnc', models.CharField(max_length=10, verbose_name='MNC')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('mechanical_tilt', models.FloatField(blank=True, null=True, verbose_name='Mechanical Tilt')),
                ('electrical_tilt', models.FloatField(blank=True, null=True, verbose_name='Electrical Tilt')),
                ('azimuth', models.FloatField(blank=True, null=True, verbose_name='Azimuth')),
                ('antenna_height', models.FloatField(blank=True, null=True, verbose_name='Antenna Height')),
                ('antenna_beam_width', models.FloatField(blank=True, null=True, verbose_name='Antenna Beam Width')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '2G Site Information',
                'verbose_name_plural': '2G Sites Information',
                'unique_together': {('site_id', 'cell_id')},
            },
        ),
        migrations.CreateModel(
            name='ThreeGSiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnc', models.CharField(max_length=100, verbose_name='RNC')),
                ('site_id', models.CharField(max_length=100, verbose_name='Site ID')),
                ('cell_id', models.CharField(max_length=100, verbose_name='Cell ID')),
                ('full_site_name', models.CharField(max_length=200, verbose_name='Full Site Name')),
                ('cell_name', models.CharField(max_length=200, verbose_name='Cell Name')),
                ('lac', models.CharField(max_length=50, verbose_name='LAC')),
                ('geo_city', models.CharField(max_length=100, verbose_name='Geo-City')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('azimuth', models.FloatField(blank=True, null=True, verbose_name='Azimuth')),
                ('mechanical_tilt', models.FloatField(blank=True, null=True, verbose_name='Mechanical Tilt')),
                ('electrical_tilt', models.FloatField(blank=True, null=True, verbose_name='Electrical Tilt')),
                ('antenna_height', models.FloatField(blank=True, null=True, verbose_name='Antenna Height')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '3G Site Information',
                'verbose_name_plural': '3G Sites Information',
                'unique_together': {('site_id', 'cell_id')},
            },
        ),
        migrations.CreateModel(
            name='FourGSiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100, verbose_name='Site ID')),
                ('cell_id', models.CharField(max_length=100, verbose_name='Cell ID')),
                ('province_id', models.CharField(max_length=10, verbose_name='Province ID')),
                ('geo_city', models.CharField(max_length=100, verbose_name='GEO City')),
                ('full_site_name', models.CharField(max_length=200, verbose_name='Full Site Name')),
                ('cell_name', models.CharField(max_length=200, verbose_name='Cell Name')),
                ('technology', models.CharField(default='4G', max_length=10, verbose_name='Technology')),
                ('lac_tac', models.CharField(max_length=50, verbose_name='LAC/TAC')),
                ('antenna_height', models.FloatField(blank=True, null=True, verbose_name='Antenna Height')),
                ('azimuth', models.FloatField(blank=True, null=True, verbose_name='Azimuth')),
                ('rf_plan_longitude', models.FloatField(verbose_name='RF Plan Longitude')),
                ('rf_plan_latitude', models.FloatField(verbose_name='RF Plan Latitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '4G Site Information',
                'verbose_name_plural': '4G Sites Information',
                'unique_together': {('site_id', 'cell_id')},
            },
        ),
    ]
