# Generated by Django 3.2.10 on 2024-10-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(max_length=100)),
                ('site_enbid', models.CharField(max_length=100, unique=True)),
                ('cell_id', models.CharField(max_length=100)),
                ('site_name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('bore', models.FloatField(blank=True, null=True)),
                ('lac_cell_id_ecgi', models.CharField(max_length=100)),
            ],
        ),
    ]
