# Generated by Django 3.2.10 on 2025-05-28 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='threegsiteinformation',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='threegsiteinformation',
            table='api_threegsiteinformation',
        ),
    ]
