# Generated by Django 3.2.10 on 2025-05-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250528_0919'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fourgsiteinformation',
            unique_together=set(),
        ),
    ]
