# Generated by Django 3.2.10 on 2024-10-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_siteinfo_site_enbid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sheet_owner_number', models.CharField(max_length=20)),
                ('filtered_calls', models.JSONField()),
                ('imei_usage', models.JSONField()),
                ('most_visited_sites', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(max_length=100)),
                ('site_enb_id', models.CharField(max_length=100)),
                ('cell_id', models.CharField(max_length=100)),
                ('site_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('bore', models.FloatField()),
                ('lac_cell_id_ecgi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInformationUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='site_information/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SiteInfo',
        ),
    ]
