# Generated by Django 3.2.10 on 2025-05-28 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_fourgsiteinformation_unique_together'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='threegsiteinformation',
            table=None,
        ),
    ]
