# Generated by Django 3.2.10 on 2025-05-28 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_threegsiteinformation_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='threegsiteinformation',
            table='api_threegsiteinformation',
        ),
    ]
