# Generated by Django 3.2.10 on 2025-07-28 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_alter_threegsiteinformation_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الدور')),
                ('display_name', models.CharField(max_length=100, verbose_name='الاسم المعروض')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('permissions', models.JSONField(default=dict, verbose_name='الصلاحيات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_system_role', models.BooleanField(default=False, verbose_name='دور النظام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دور',
                'verbose_name_plural': 'الأدوار',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255, unique=True, verbose_name='مفتاح الجلسة')),
                ('device_info', models.JSONField(default=dict, verbose_name='معلومات الجهاز')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('user_agent', models.TextField(verbose_name='متصفح المستخدم')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع الجغرافي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('expires_at', models.DateTimeField(verbose_name='انتهاء الصلاحية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='آخر نشاط')),
                ('requests_count', models.PositiveIntegerField(default=0, verbose_name='عدد الطلبات')),
                ('last_request_path', models.CharField(blank=True, max_length=500, verbose_name='آخر صفحة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جلسة مستخدم',
                'verbose_name_plural': 'جلسات المستخدمين',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('activation_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التفعيل')),
                ('deactivation_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إلغاء التفعيل')),
                ('account_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهاء صلاحية الحساب')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخر IP تسجيل دخول')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, verbose_name='محاولات تسجيل دخول فاشلة')),
                ('account_locked_until', models.DateTimeField(blank=True, null=True, verbose_name='الحساب مقفل حتى')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='يجب تغيير كلمة المرور')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تغيير لكلمة المرور')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.role', verbose_name='الدور')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('create', 'إنشاء'), ('update', 'تحديث'), ('delete', 'حذف'), ('view', 'عرض'), ('upload', 'رفع'), ('download', 'تحميل'), ('search', 'بحث'), ('analyze', 'تحليل'), ('password_change', 'تغيير كلمة مرور'), ('failed_login', 'محاولة دخول فاشلة'), ('account_locked', 'قفل حساب')], max_length=50, verbose_name='النشاط')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نموذج البيانات')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكائن')),
                ('changes', models.JSONField(default=dict, verbose_name='التغييرات')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('user_agent', models.TextField(verbose_name='متصفح المستخدم')),
                ('session_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='مفتاح الجلسة')),
                ('success', models.BooleanField(default=True, verbose_name='نجح')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت الحدث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'نشاط مستخدم',
                'verbose_name_plural': 'نشاطات المستخدمين',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('failed_login', 'محاولة دخول فاشلة'), ('account_locked', 'قفل حساب'), ('suspicious_activity', 'نشاط مشبوه'), ('multiple_sessions', 'جلسات متعددة'), ('permission_violation', 'انتهاك صلاحيات'), ('data_access', 'وصول للبيانات الحساسة')], max_length=50, verbose_name='نوع التنبيه')),
                ('severity', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], max_length=20, verbose_name='مستوى الخطورة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('details', models.JSONField(default=dict, verbose_name='التفاصيل')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم الحل')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='ملاحظات الحل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='حل بواسطة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تنبيه أمني',
                'verbose_name_plural': 'التنبيهات الأمنية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'timestamp'], name='api_useract_user_id_ae111e_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['action', 'timestamp'], name='api_useract_action_0f403f_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['ip_address', 'timestamp'], name='api_useract_ip_addr_b628d6_idx'),
        ),
    ]
