# Generated by Django 3.2.10 on 2025-08-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_user_analysis_results'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='useranalysisresult',
            name='api_useranal_user_id_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='useranalysisresult',
            name='api_useranal_expires_at_idx',
        ),
        migrations.AddField(
            model_name='useranalysisresult',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='useranalysisresult',
            index=models.Index(fields=['user', '-created_at'], name='api_userana_user_id_e58201_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalysisresult',
            index=models.Index(fields=['expires_at'], name='api_userana_expires_29c8b4_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalysisresult',
            index=models.Index(fields=['last_accessed'], name='api_userana_last_ac_d26e75_idx'),
        ),
    ]
